feat: query arg propertyies
chargetrip/developers pull request #139
Opened 2021-09-01 08:21 UTC by Laurensvdmaas

2021-09-02 11:14 UTC, Wouter125 requested changes

2021-09-02 11:14 UTC, Wouter125 commented on components/globals/Playground.vue
> +    var(--body) 0%,
We got them available in the package then right? So we could grab them from there?

2021-09-02 11:14 UTC, Wouter125 commented on layouts/default.vue
> +    console.log(this.$cloudinaryFolder)
```suggestion
```

2021-09-02 11:14 UTC, Wouter125 commented on scripts/schema.js
> +    }
```suggestion
```

Don't need this debuggin anymore.

2021-09-02 11:14 UTC, Wouter125 commented on tailwind.config.js
> +        0: 0,
Why should we include a font-size of 0?

2021-09-02 11:14 UTC, imjasonmiller commented on nuxt.config.js
> +    CLUDINARY_FOLDER: process.env.CLUDINARY_FOLDER,
Nit: should this be `CLOUDINARY_FOLDER`?

2021-09-02 11:15 UTC, Wouter125 commented on nuxt.config.js
> +    CLUDINARY_FOLDER: process.env.CLUDINARY_FOLDER,
Yea added it as a suggestion above :)

2021-09-02 11:21 UTC, imjasonmiller commented on layouts/default.vue
> +    console.log(this.$cloudinaryFolder)
Is this perhaps related to the environment variable from `nuxt.config.js`?

2021-09-02 11:31 UTC, imjasonmiller requested changes
It looks great! I've left a couple of comments that might be addressed before merging, but these are nits.

2021-09-03 07:32 UTC, Laurensvdmaas commented on components/globals/Playground.vue
> +    var(--body) 0%,
They go from 80 -> 100 that's why i put them there, removed the up to down ones.

2021-09-03 07:33 UTC, Laurensvdmaas commented on nuxt.config.js
> +    CLUDINARY_FOLDER: process.env.CLUDINARY_FOLDER,
This is not necessary anymore, removed.

2021-09-03 07:40 UTC, Laurensvdmaas commented on tailwind.config.js
> +        0: 0,
It's in the component library, usually it's used to remove the space between `display: inline-block` items

2021-09-03 07:41 UTC, Laurensvdmaas commented on nuxt.config.js
> +    CLUDINARY_FOLDER: process.env.CLUDINARY_FOLDER,
Removed this line, not necessary anymore

2021-09-03 08:24 UTC, Wouter125 approved these changes

2021-09-03 08:25 UTC, merged